title: "Titre de ton projet"
description: "Description de ton projet"
baseurl: "" # Ne rien mettre ici pour l'instant
theme: null

include:
  - theme

layouts_dir: theme/_layouts
sass:
  sass_dir: theme/assets/css